pipeline:
  build_docker_image:
    image: docker:17.05
    secrets: [ docker_username, docker_password ]
    environment:
      - DOCKER_HOST=tcp://127.0.0.1:2375
      - TAG=${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:8}
    commands:
      - docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}" docker.registry.spawnhub.com
      - docker build -t image .
      - docker tag image docker.registry.spawnhub.com/hello-drone-helm:latest
      - docker tag image docker.registry.spawnhub.com/hello-drone-helm:${TAG}
      - docker push docker.registry.spawnhub.com/hello-drone-helm

services:
  dind:
    image: docker:17.05-dind
    privileged: true
    command:
      - "-s"
      - "overlay"
  # helm_deploy_staging:
  #   image: quay.io/honestbee/drone-helm
  #   skip_tls_verify: true
  #   helm_repos: public-charts=http://tech.honestbee.com/public-charts
  #   chart: public-charts/hello-world
  #   values: image.repository=quay.io/honestbee/hello-drone-helm,image.tag=${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:7}
  #   release: ${DRONE_REPO_NAME}-${DRONE_BRANCH}
  #   prefix: STAGING
  #   when:
  #     branch:
  #       exclude: [ master ]
